env:

  ARTIFACT_BUCKET: s3://ci-output-sink

steps:

  # XXX: `</dev/null turns off any interactive questions from Nix (e.g. accept-flake-config)

  - label: 'sign-in-derivation'
    command: 'nix </dev/null run --no-accept-flake-config -L .#packages.x86_64-darwin.signingTest.inDerivation'
    agents:
      queue: lace
      system: x86_64-darwin

  - label: 'sign-outside-of-derivation'
    command: 'nix </dev/null run --no-accept-flake-config -L .#packages.x86_64-darwin.signingTest.outsideOfDerivation'
    agents:
      queue: lace
      system: x86_64-darwin
